name: gidc2
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy<2.0
  - cudatoolkit=11.3
  - cudnn=8.2.1
  - matplotlib
  - scipy
  - pip
  - pip:
    - tensorflow-gpu==2.10.0